(define (domain elevators)
    (:requirements :strips :typing :fluents :durative-actions :continuous-effects) 
  (:types floor block movable - object
          elevator person - movable
          fast-elevator slow-elevator - elevator)
  
  (:predicates (at-floor ?m - movable ?f - floor)
               (at-elevator ?p - person ?l - elevator)
               (part-of ?e - elevator ?b - block)
               (serves ?e - elevator ?f - floor)
               (above ?f1 - floor ?f2 - floor)
               )
  (:functions
           (elevator-capacity ?cap - elevator)
           (distance ?f1 - floor ?f2 - floor)
           (time-per-floor ?e - elevator)
           (up-warm-up-time ?e - elevator)
           (down-warm-up-time ?e - elevator)
           (move-cost ?e - elevator)
           (person-cost ?e - elevator)
           (building-energy)
           (total-energy-used)
           )

  (:durative-action GET-IN
	   :parameters (?p - person ?e - elevator ?f - floor)
	   :duration (= ?duration 2)
	   :condition (and (at start (at-floor ?p ?f))
                       (over all (at-floor ?e ?f))
 			           (at start (> (elevator-capacity ?e) 0))
 			              )
	   :effect (and (at end   (at-elevator ?p ?e))
                    (at start (not (at-floor ?p ?f)))
                    (at start (decrease (elevator-capacity ?e) 1))))

  (:durative-action GET-OUT
	   :parameters (?p - person ?e - elevator ?f - floor)
	   :duration (= ?duration 2)
	   :condition (and (at start (at-elevator ?p ?e))
                       (over all (at-floor ?e ?f))
 			              )
	   :effect (and (at start (not (at-elevator ?p ?e)))
                    (at end   (at-floor ?p ?f))
                    (at start (increase (elevator-capacity ?e) 1))))

  (:durative-action MOVE-UP---------------------
	   :parameters (?e - elevator ?f1 - floor ?f2 - floor)
	   :duration (= ?duration (+ (up-warm-up-time ?e) (* (time-per-floor ?e) 
	                                                     (distance ?f1 ?f2))))
	   :condition (and (over all (serves ?e ?f1))
                       (over all (serves ?e ?f2))
                       (at start (at-floor ?e ?f1))
                       (at start (above ?f2 ?f1))
                       (at start (>= (building-energy) (* (* (move-cost ?e) 
                                                             (- 4 (elevator-capacity ?e))) 
                                                          (* (distance ?f1 ?f2) 
                                                             (/ (distance ?f1 ?f2) 
                                                                 (+ (up-warm-up-time ?e) (time-per-floor ?e))))))))
	   :effect (and (at start (not (at-floor ?e ?f1)))
                    (at end (at-floor ?e ?f2))
                    (at start (decrease (building-energy) (* (* (move-cost ?e) 
                                                                (- 4 (elevator-capacity ?e)))
                                                             (* (distance ?f1 ?f2)
                                                                (/ (distance ?f1 ?f2) 
                                                                    (+ (up-warm-up-time ?e) (time-per-floor ?e)))))))
                    (at end (increase (total-energy-used) (* (* (move-cost ?e) 
                                                                (- 4 (elevator-capacity ?e))) 
                                                             (* (distance ?f1 ?f2) 
                                                                (/ (distance ?f1 ?f2) 
                                                                   (+ (up-warm-up-time ?e) (time-per-floor ?e)))))))))

  (:durative-action MOVE-DOWN---------------------
	   :parameters (?e - elevator ?f1 - floor ?f2 - floor)
	   :duration (= ?duration (+ (down-warm-up-time ?e) (* (time-per-floor ?e) (distance ?f1 ?f2))))
	   :condition (and (over all (serves ?e ?f1))
                       (over all (serves ?e ?f2))
                       (at start (at-floor ?e ?f1))
                       (at start (above ?f1 ?f2))
                          )
	   :effect (and (at start (not (at-floor ?e ?f1)))
                    (at end (at-floor ?e ?f2))
                    (at start (decrease (building-energy) (* (* (move-cost ?e) 
                                                                (- (elevator-capacity ?e) 3))
                                                             (* (distance ?f1 ?f2)
                                                                (/ (distance ?f1 ?f2) 
                                                                   (+ (down-warm-up-time ?e) (time-per-floor ?e)))))))
                    (at end (increase (total-energy-used) (* (* (move-cost ?e) 
                                                                (- (elevator-capacity ?e) 3))
                                                             (* (distance ?f1 ?f2) 
                                                                (/ (distance ?f1 ?f2) 
                                                                   (+ (down-warm-up-time ?e) (time-per-floor ?e)))))))))
  (:durative-action CHARGE-BATTERIES-FROM-SOLAR
      :duration (= ?duration 10)
      :condition (and (at start (>= (building-energy) -1000)))
      :effect (and (at end (increase (building-energy) 50)))
  )
)
